### PR TITLE
fix: export named `fetch` from `node-fetch` polyfill

### PR DESCRIPTION
**Pull request by danielroe**
### ❓ Type of change

- [ ] 📖 Documentation (updates to the documentation or readme)
- [x] 🐞 Bug fix (a non-breaking change that fixes an issue)
- [ ] 👌 Enhancement (improving an existing functionality like performance)
- [ ] ✨ New feature (a non-breaking change that adds functionality)
- [ ] ⚠️ Breaking change (fix or feature that would cause existing functionality to change)

### 📚 Description

This adds a named fetch export for compatibility with `node-fetch-native`: https://github.com/unjs/node-fetch-native/blob/main/src/index.ts#L12.

### 📝 Checklist

- [ ] I have linked an issue or discussion.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

**Review by pi0 — APPROVED** [review]

**Comment by pi0** [comment]
Seems a nice addition btw we are not aliasing `node-fetch-native` itself ([src](https://github.com/unjs/unenv/blob/4dcf17d574d370af43bc919582f1e380d1aa94cb/src/presets/node.ts#L5)). Wondering what was the original issue?

**Comment by rvmourik** [comment]
@danielroe do you know when there will be a tagged release with this commit? We encounter this error and it stops us from deploying our newly migrated Nuxt3 website to Cloudflare workers.

Thanks in advance 🙏

**Comment by danielroe** [comment]
You should now be able to benefit from this from `v1.0.1` ❤️

**Comment by rvmourik** [comment]
> You should now be able to benefit from this from `v1.0.1` ❤️

Thanks, works perfectly.

**Pull request merged**
